version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install time
      - export BUCKET=
      - aws cloudformation package --template-file time-sam-template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - time-sam-template.yaml
    - outputtemplate.yaml
