version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - ls -al
      - env
      - npm install -g serverless
  build:
    commands:
      - cd services/dynamodb
      - ls -al
      - serverless deploy -v
