service: metaphoto-dynamodb

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: metaphoto-${self:custom.stage}
  tableThroughputs:
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-1
  deploymentBucket: net.ajmiller.${self:provider.region}.serverless.deployments

resources:
  Resources:
    MediaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: mediaId
            AttributeType: S
          - AttributeName: mediaType
            AttributeType: S
        KeySchema:
          - AttributeName: mediaId
            KeyType: HASH
          - AttributeName: mediaType
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

  Outputs:
    MediaTableArn:
      Value: !GetAtt MediaTable.Arn
      Export:
        Name: ${self:custom.stage}-MediaTableArn
