AWSTemplateFormatVersion: '2010-09-09'
Description: Shared infrastructure for Metaphoto, including build pipelines, dynamodb tables, S3 buckets, and IAM roles

Parameters:
  Environment:
    AllowedValues:
      - dev
      - prod
    Description: 'Environment'
    Type: 'String'
    Default: 'dev'

  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'

  GitHubOwner:
    Type: String
    Default: allenmiller
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: metaphoto
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"

  ApplicationStackName:
    Type: String
    Default: metaphoto
    AllowedPattern: "[A-Za-z0-9-]+"

  HostedZoneDnsName:
    Type: String
    Default: metaphoto.ajmiller.net

  UsEast1CertificateArn:
    Type: String
    Description: ARN of certificate in us-east-1 for use by Cloudfront

Resources:
  MetaphotoPipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  MetaphotoDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  MediaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["-", [metaphoto, !Ref Environment]]
      AttributeDefinitions:
        - AttributeName: mediaId
          AttributeType: S
        - AttributeName: mediaType
          AttributeType: S
      KeySchema:
        - AttributeName: mediaId
          KeyType: HASH
        - AttributeName: mediaType
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  MetaphotoHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: Hosted zone for metaphoto
      Name: !Ref HostedZoneDnsName

  TlsCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join [".", ["*", !Ref HostedZoneDnsName]]
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Join [".", ["*", !Ref HostedZoneDnsName]]
        - !Ref HostedZoneDnsName

  MetaphotoDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Aliases:
          - metaphoto.ajmiller.net
        ViewerCertificate:
          AcmCertificateArn: !Ref UsEast1CertificateArn
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
        Origins:
          -
            # Use the DeployBucket as the CDN origin
            DomainName: !GetAtt MetaphotoPipelineArtifactsBucket.DomainName
            Id: !Ref MetaphotoPipelineArtifactsBucket
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultRootObject: index.html
        Enabled: true
        # Configure the caching behavior for our CDN
        DefaultCacheBehavior:
          MinTTL: 86400  # 1 day
          MaxTTL: 31536000  # 1 year
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref MetaphotoPipelineArtifactsBucket
          ViewerProtocolPolicy: "redirect-to-https"   # we want to force HTTPS

  TimeLambdaCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: TimeLambdaCodeBuildProject
      Description: Set up the time lambda
      ServiceRole: !Ref LambdaCodeBuildRole
      TimeoutInMinutes: 5
      Source:
        Type: CODEPIPELINE
        BuildSpec: services/time/buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.1.0
      Artifacts:
        Type: CODEPIPELINE

  WebAppCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: WebAppCodeBuildProject
      ServiceRole: !Ref WebAppCodeBuildRole
      Artifacts:
        # The downloaded source code for the build will come from CodePipeline
        Type: CODEPIPELINE
        Name: MyProject
      Environment:
        # Linux container with node installed
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: aws/codebuild/nodejs:10.1.0
        EnvironmentVariables:
          - Name: DeployBucket
            Value: !Ref MetaphotoPipelineArtifactsBucket
          - Name: Distribution
            Value: !Ref MetaphotoDistribution
      Source:
        Type: CODEPIPELINE
        BuildSpec: webapp/metaphoto-client/buildspec.yml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref MetaphotoPipelineArtifactsBucket
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1

        - Name: BuildAndDeploy
          Actions:
            - Name: TimeLambda
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceCode
              Configuration:
                ProjectName: !Ref TimeLambdaCodeBuildProject

            - Name: WebApp
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: DeployedWebApp
              Configuration:
                ProjectName: !Ref WebAppCodeBuildProject

  GithubWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      RegisterWithThirdParty: 'true'
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        'Fn::Join': [ "-", ["CodeBuildRole", !Ref 'AWS::StackName', !Ref 'Environment']]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"
          Action: "sts:AssumeRole"

  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join [ "-", ["CodePipelineRole", !Ref 'AWS::StackName', !Ref 'Environment']]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: "codepipeline.amazonaws.com"
          Action: "sts:AssumeRole"

  DynamoDbCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", ["DynamoDbCodeBuildRole", !Ref "AWS::StackName"] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"
          Action: "sts:AssumeRole"

  LambdaCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", ["LambdaCodeBuildRole", !Ref "AWS::StackName"] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"
          Action: "sts:AssumeRole"

  WebAppCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", ["WebAppCodeBuildRole", !Ref "AWS::StackName"] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"
          Action: "sts:AssumeRole"

  DynamoDBCodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join [ "-", ["DynamoDbCodeBuildPolicy", !Ref "AWS::StackName"] ]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - DynamoDB:CreateTable
            - DynamoDB:DescribeTable
            - DynamoDB:TagResource
          Resource: "*"
      Roles:
        - !Ref DynamoDbCodeBuildRole

  LoggingPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        'Fn::Join': [ "-", ["LoggingPolicy", !Ref 'AWS::StackName', !Ref 'Environment']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:FilterLogEvents
            - logs:DescribeLogStreams
            - logs:DeleteLogGroup
          Resource: "*"
      Roles:
        - !Ref DynamoDbCodeBuildRole
        - !Ref LambdaCodeBuildRole
        - !Ref WebAppCodeBuildRole

  CodebuildCloudformationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        'Fn::Join': [ "-", ["CodebuildCloudformationPolicy", !Ref 'AWS::StackName', !Ref 'Environment']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - Cloudformation:DescribeStacks
            - Cloudformation:DescribeStackEvents
            - Cloudformation:DescribeStackResource
            - Cloudformation:ListStackResources
            - Cloudformation:ValidateTemplate
            - Cloudformation:CreateStack
            - Cloudformation:CreateUploadBucket
            - Cloudformation:DeleteStack
            - Cloudformation:UpdateStack
          Resource: "*"
      Roles:
        - !Ref DynamoDbCodeBuildRole
        - !Ref LambdaCodeBuildRole

  S3PutGetPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName:
        'Fn::Join': [ "-", ["S3PutGetPolicy", !Ref 'AWS::StackName', !Ref 'Environment']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - S3:ListBucket
            - S3:GetBucketLocation
            - S3:GetObject
            - S3:PutObject
            - S3:PutObjectAcl
          Resource: "*"
      Roles:
        - !Ref DynamoDbCodeBuildRole
        - !Ref LambdaCodeBuildRole
        - !Ref WebAppCodeBuildRole

  LambdaCodeBuildPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName:
        'Fn::Join': [ "-", ["LambdaCodeBuildPolicy", !Ref 'AWS::StackName', !Ref 'Environment']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - ACM:ListCertificates
            - IAM:CreateRole
            - IAM:CreateServiceLinkedRole
            - IAM:GetRole
            - IAM:GetRolePolicy
            - IAM:PutRolePolicy
            - IAM:DeleteRolePolicy
            - IAM:DeleteRole
            - IAM:PassRole
            - apigateway:GET
            - apigateway:POST
            - apigateway:PUT
            - apigateway:DELETE
            - apigateway:PATCH
            - Cloudformation:GET
            - lambda:Get*
            - lambda:List*
            - lambda:CreateFunction
            - lambda:AddPermission
            - lambda:CreateAlias
            - lambda:DeleteFunction
            - lambda:InvokeFunction
            - lambda:PublishVersion
            - lambda:RemovePermission
            - lambda:UpdateFunctionCode
            - Route53:ListHostedZones
            - Route53:ChangeResourceRecordSets
            - Route53:GetHostedZone
            - Route53:ListResourceRecordSets
          Resource: "*"
      Roles:
        - !Ref LambdaCodeBuildRole

  CloudFrontDistributionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        'Fn::Join': [ "-", ["LambdaCodeBuildPolicy", !Ref 'AWS::StackName', !Ref 'Environment']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - Cloudfront:UpdateDistribution
            - Cloudfront:CreateInvalidation
          Resource: "*"
      Roles:
        - !Ref LambdaCodeBuildRole
        - !Ref WebAppCodeBuildRole

  CodeBuildPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName:
        'Fn::Join': [ "", ["CodeBuildPolicy", "-", !Ref 'AWS::StackName', "-", !Ref 'Environment']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - codebuild:*
            - s3:DeleteBucket
            - s3:ListBucketVersions
            - cloudwatch:GetMetricStatistics
            - events:Put*
            - events:Remove*
            - events:Delete*
          Resource: "*"
      Roles:
        - !Ref CodeBuildRole

  CodePipelinePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName:
        'Fn::Join': [ "-", ["CodePipelinePolicy", !Ref 'AWS::StackName', !Ref 'Environment']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - s3:*
            - codebuild:*
          Resource:
            - "*"
      Roles:
        - !Ref CodePipelineRole

Outputs:
  MetaphotoHostedZone:
    Description: Domain name for application
    Value: !Ref HostedZoneDnsName
    Export:
      Name: MetaphotoHostedZone

  MetaphotoPipelineArtifactsBucket:
    Description: Bucket to hold build artifacts
    Value: !Ref MetaphotoPipelineArtifactsBucket
    Export:
      Name: MetaphotoPipelineArtifactsBucket

  MetaphotoDataBucket:
    Description: Holds application data such as photos, film specs, etc.
    Value: !Ref MetaphotoDataBucket
    Export:
      Name: MetaphotoDataBucket

  MetaphotoHostedZoneNameServers:
    Description: Hosted zone for metaphoto.ajmiller.net
    Value: !Join
      - ' '
      - !GetAtt MetaphotoHostedZone.NameServers
    Export:
      Name: MetaphotoHostedZoneNameServers

  MetaphotoCertificateArn:
    Description: ARN for the certificate
    Value: !Ref TlsCertificate
    Export:
      Name: TlsCertificateArn

  MediaTableArn:
    Value: !GetAtt MediaTable.Arn
    Export:
      Name: MediaTableArn
