service: metaphoto-time

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-1
  deploymentBucket: ${cf:metaphoto-us-west-1-dev.MetaphotoPipelineArtifactsBucket}
  domain: ${cf:metaphoto-us-west-1-dev.MetaphotoHostedZone}

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}

  # Important: The Route53 A and AAAA domain records created by serverless-domain-manager are managed by the API,
  # not Cloudformation.  They do not appear as Resources in the Cloudformation stack for this service.  Do not manage
  # them manually via Route53.
  customDomain:
    domainName: api.${self:provider.domain}
    stage: ${self:provider.stage}
    basePath: ${self:provider.stage}
    certificateName: ${self:provider.domain}
    endpointType: REGIONAL
    createRoute53Record: true

functions:
  get:
    handler: time.handler
    events:
      - http:
          path: time
          method: get
          cors: true
