service: metaphoto-time

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-1
  deploymentBucket: ${cf:metaphoto-us-west-1-dev.MetaphotoPipelineArtifactsBucket}

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  customDomain:
    domainName: metaphoto.ajmiller.net
    stage: ${self:provider.stage}
    basePath: ${self:provider.stage}
#     certificateName: metaphoto.ajmiller.net
    certificateArn: arn:aws:acm:us-west-1:235694731559:certificate/bb6e9f07-8815-4bc9-83c2-c77d8e580161
    endpointType: REGIONAL
    createRoute53Record: true

functions:
  get:
    handler: time.handler
    events:
      - http:
          path: time
          method: get
          cors: true
